// AUTOGENERATED FILE
// This file was generated from sql.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode,
} from "ohm-js";

export interface SQLActionDict<T> extends BaseActionDict<T> {
  Statement?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  SelectStatement?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: IterationNode,
    arg2: NonterminalNode,
    arg3: NonterminalNode,
    arg4: NonterminalNode,
    arg5: IterationNode,
    arg6: IterationNode,
    arg7: IterationNode,
    arg8: IterationNode,
    arg9: IterationNode,
    arg10: IterationNode,
    arg11: IterationNode,
  ) => T;
  Distinct_on?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: TerminalNode,
    arg3: NonterminalNode,
    arg4: TerminalNode,
  ) => T;
  Distinct_plain?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Distinct?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnList?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnEntry_aliased?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  ColumnEntry_plain?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnEntry?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnExpr_func?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnExpr_qualifiedWild?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnExpr_wild?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnExpr_qualified?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnExpr_simple?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  FuncCall?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
    arg3: TerminalNode,
  ) => T;
  FuncArgs_distinct?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  FuncArgs_plain?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  FuncArgs_wildcard?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  FuncArgs_empty?: (this: NonterminalNode) => T;
  FuncArgs?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  FuncArgList?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  qualifiedWildcard?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: TerminalNode,
  ) => T;
  qualifiedName?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
  ) => T;
  wildcard?: (this: NonterminalNode, arg0: TerminalNode) => T;
  TableRef_aliased?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  TableRef_implicitAlias?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
  ) => T;
  TableRef_plain?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  TableRef?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  TableName_qualified?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
  ) => T;
  TableName_simple?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  TableName?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  JoinClause_typed?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
    arg3: NonterminalNode,
  ) => T;
  JoinClause_cross?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  JoinClause_natural?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  JoinClause?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  JoinType_innerOuter?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  JoinType_inner?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  JoinType_leftOuter?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  JoinType_left?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  JoinType_rightOuter?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  JoinType_right?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  JoinType_fullOuter?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  JoinType_full?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  JoinType?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  JoinCondition_on?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  JoinCondition_using?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
    arg3: TerminalNode,
  ) => T;
  JoinCondition?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereClause?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  WhereExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereOrExpr_or?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  WhereOrExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereAndExpr_and?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  WhereAndExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WherePrimary_paren?: (
    this: NonterminalNode,
    arg0: TerminalNode,
    arg1: NonterminalNode,
    arg2: TerminalNode,
  ) => T;
  WherePrimary_not?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  WherePrimary?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereComparison_compare?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  WhereComparison_isNotNull?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
    arg3: NonterminalNode,
  ) => T;
  WhereComparison_isNull?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  WhereComparison?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  compOp?: (this: NonterminalNode, arg0: TerminalNode) => T;
  WhereValue_func?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereValue_string?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereValue_float?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereValue_integer?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereValue_bool?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereValue_null?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereValue_columnRef?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereValue?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnRef_qualified?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
  ) => T;
  ColumnRef_simple?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnRef?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  stringLiteral?: (
    this: NonterminalNode,
    arg0: TerminalNode,
    arg1: IterationNode,
    arg2: TerminalNode,
  ) => T;
  floatLiteral?: (
    this: NonterminalNode,
    arg0: IterationNode,
    arg1: TerminalNode,
    arg2: IterationNode,
  ) => T;
  boolLiteral?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  GroupByClause?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  HavingClause?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  OrderByClause?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  OrderByItem?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: IterationNode,
    arg2: IterationNode,
  ) => T;
  OrderDirection_asc?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  OrderDirection_desc?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  OrderDirection?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  NullsOrder_first?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  NullsOrder_last?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  NullsOrder?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  LimitClause?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  OffsetClause?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  identifier?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  integer?: (this: NonterminalNode, arg0: IterationNode) => T;
  select?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  from?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  as?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  where?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  and?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  or?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  limit?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  not?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  null?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  is?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  join?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  inner?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  left?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  right?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  full?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  outer?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  cross?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  natural?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  on?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  using?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  order?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  by?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  group?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  having?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  distinct?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  asc?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  desc?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  nulls?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  first?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  last?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  offset?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  keyword?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  identPart?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  space?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  lineComment?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
}

export interface SQLSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: SQLActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: SQLActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: SQLActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: SQLActionDict<T>): this;
}

export interface SQLGrammar extends Grammar {
  createSemantics(): SQLSemantics;
  extendSemantics(superSemantics: SQLSemantics): SQLSemantics;
}

declare const grammar: SQLGrammar;
export default grammar;
