// AUTOGENERATED FILE
// This file was generated from sql.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode,
} from "ohm-js";

export interface SQLActionDict<T> extends BaseActionDict<T> {
  Statement?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  SelectStatement?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
    arg3: NonterminalNode,
    arg4: IterationNode,
    arg5: IterationNode,
  ) => T;
  ColumnList?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnEntry_aliased?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  ColumnEntry_plain?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnEntry?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnExpr_qualifiedWild?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnExpr_wild?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnExpr_qualified?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnExpr_simple?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  qualifiedWildcard?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: TerminalNode,
  ) => T;
  qualifiedName?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
  ) => T;
  wildcard?: (this: NonterminalNode, arg0: TerminalNode) => T;
  TableRef_aliased?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  TableRef_implicitAlias?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
  ) => T;
  TableRef_plain?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  TableRef?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  TableName_qualified?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
  ) => T;
  TableName_simple?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  TableName?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereClause?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  WhereExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereOrExpr_or?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  WhereOrExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereAndExpr_and?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: NonterminalNode,
    arg2: NonterminalNode,
  ) => T;
  WhereAndExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WherePrimary_paren?: (
    this: NonterminalNode,
    arg0: TerminalNode,
    arg1: NonterminalNode,
    arg2: TerminalNode,
  ) => T;
  WherePrimary?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WhereComparison?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
  ) => T;
  ColumnRef_qualified?: (
    this: NonterminalNode,
    arg0: NonterminalNode,
    arg1: TerminalNode,
    arg2: NonterminalNode,
  ) => T;
  ColumnRef_simple?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ColumnRef?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  stringLiteral?: (
    this: NonterminalNode,
    arg0: TerminalNode,
    arg1: IterationNode,
    arg2: TerminalNode,
  ) => T;
  LimitClause?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  identifier?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  integer?: (this: NonterminalNode, arg0: IterationNode) => T;
  select?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  from?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  as?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  where?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  and?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  or?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  limit?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  keyword?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  identPart?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  space?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  lineComment?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
}

export interface SQLSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: SQLActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: SQLActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: SQLActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: SQLActionDict<T>): this;
}

export interface SQLGrammar extends Grammar {
  createSemantics(): SQLSemantics;
  extendSemantics(superSemantics: SQLSemantics): SQLSemantics;
}

declare const grammar: SQLGrammar;
export default grammar;
